version: '2'
services:
    flask:
        build: .
        container_name: web_flask
        image: crazw/flask
        ports:
            - "5000:5000"
        volumes:
            - ./code:/code
        depends_on:
            - redis
    redis:
        container_name: web_redis
        image: redis
